"""
=========================================================================
						BACKUP AND RESTORATION
=========================================================================
This section covers the main methods for creating and restoring backups 
in PostgreSQL, ensuring data protection and recovery in case of failures.
-------------------------------------------------------------------------

## Backup with pg_dump
pg_dump is a tool used to create a backup of a single database. 
It can export the database schema and/or its data into a file, 
which can later be restored using SQL commands or dedicated utilities.

## Backup with pg_dumpall
pg_dumpall is used to back up all databases within a PostgreSQL server, 
including global objects such as roles and configurations. It’s ideal 
for making a complete backup of the entire PostgreSQL instance.

## Restoration simple (psql)
A simple restoration uses psql, the PostgreSQL command-line client, 
to import a backup file generated by pg_dump (usually in SQL format). 
It’s a straightforward and efficient way to rebuild a database.

## Restoration with pg_restore
pg_restore is used to restore backups created by pg_dump in custom 
or compressed formats. It provides more control over the restoration 
process — for example, restoring specific tables or schemas, and 
applying selective recovery options.
"""

# Backup with pg_dump using command line (cmd)
# Use the pg_dump --help command to list all option
pg_dump -d [database_name] -h [hostname] -p [port] -U [username] -f "path/file_backup_name.bkp" [--option]
pg_dump -d [database_name] -h [hostname] -p [port] -U [username] -Fc -f "path/file_backup_name_customer.bkp" [--option] # Used for pg_restore

# Backup with pg_dumpall```
pg_dumpall -h [hostname] -p [port] -U [username] -f "path/file_backup_name.bkp" [--option]

# Restoration simple (psql)```
psql -h [hostname] -p [port] -U [username] -f "/path/file_backup_name_create_before.bkp"

# Restoration with pg_restore
psql -h [hostname] -p [port] -U [username] -d [database_name] "/path/file_backup_name_customer.bkp.bkp"
